repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
# sorts imports by alphabetically and into base>packages>local
-   repo: https://github.com/PyCQA/isort
    rev: '5.7.0'
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile black]
# Run black formatter
-   repo: https://github.com/psf/black
    rev: '22.1.0'
    hooks:
    -   id: black
# pylint relies on local imports a venv will fail to import locally installed
# pakages hence repo = local
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint --rcfile=.pylintrc
        language: system
        types: [python]
        args: [--errors-only]
